modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/FriendlyEndermite/issues"
license="GNU General Public License v3.0"

[[mods]]
	modId="friendermite"
	version="${file.jarVersion}"
	displayName="Friendermite"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/friendlyendermite"
	authors=["CreativeMD"]
	description='''Endermans will not attack Endermites anymore, so they cannot be used to make an Enderman farm.'''
	