modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/FriendlyEndermite/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="friendermite"
    logoFile="friendermite.png"
    version="1.0.6"
    displayName="Friendermite"
    displayURL="https://modrinth.com/mod/friendermite"
    authors="CreativeMD"
    description='''Endermans will not attack Endermites anymore, so they cannot be used to make an Enderman farm.'''

[[dependencies.friendermite]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.friendermite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

